---
- name: Find all files
  find:
    paths: 'templates/docker-compose/{{ outer.type }}'
    file_type: file
    recurse: true
    hidden: true
  register: files

- name: Render templates
  ansible.builtin.template:
    src: '{{ item.path }}'
    dest: '/etc/docker-compose/{{ outer.name }}/{{ item.path | regex_replace("templates\/docker-compose\/" + outer.type + "\/" , "") | regex_replace("\.j2", "") }}'
    mode: '644'
  vars:
    svc_config: "{{ outer.config }}"
  loop: "{{ files.files }}"

