---
- name: Install docker and docker-compose
  import_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
    docker_install_compose: fa1lse

- name: Create root directory
  file:
    path: '/etc/docker-compose'
    state: 'directory'
    mode: '750'

- name: Create directories
  file:
    path: '/etc/docker-compose/{{ item.name }}'
    state: 'directory'
    mode: '755'
  loop: '{{ docker_compose_services }}'

- name: Deploy individual service
  include_tasks: docker_svc.yml
  loop: '{{ docker_compose_services }}'
  loop_control:
    loop_var: outer

- name: Copy systemd template
  ansible.builtin.copy:
    src: systemd-docker-compose.service
    dest: /etc/systemd/system/docker-compose@.service
    mode: '400'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Set up reload cronjob
  ansible.builtin.cron:
    name: "docker service reload"
    minute: "0"
    hour: "4"
    job: "/bin/systemctl reload docker-compose@*.service"

- name: Set up prune cronjob
  ansible.builtin.cron:
    name: "docker prune"
    minute: "0"
    hour: "5"
    weekday: "4"
    job: "/usr/bin/docker system prune --force > /dev/null"

- name: Enable docker-compose services
  ansible.builtin.systemd:
    name: 'docker-compose@{{ item.name }}'
    enabled: true
    state: started
  loop: '{{ docker_compose_services }}'

